server:
  port: 3000
google:
  oauth2-endpoint: 'https://oauth2.googleapis.com'
  credential-config-path: 'credentials/credentials.properties'
  drive:
    api:
      endpoint: 'https://www.googleapis.com/drive/v3'
witai:
  api:
    version: '20200513'
    endpoint: 'https://api.wit.ai'
intent:
  config: 'intent/IntentConfiguration.json'